### ISSUE TITLE
Add `persisted?` method

### ISSUE THREAD

**Issue by danielpclark** [tbrand/topaz#11]
I'd like to check if a model is persisted.  It will help with validations later too.

```crystal
class Thing < Topaz::Model
  columns(
    description: String
  )
end

x = Thing.new("a")
x.persisted?
# => false
x.save
x.persisted?
# => true

y = Thing.create("b")
y.persisted?
# => true
```

**Comment by danielpclark** [comment]
Rails defines it as

```crystal
# File activerecord/lib/active_record/persistence.rb
def persisted?
  !(new_record? || destroyed?)
end
```

So maybe we can add these methods as well?

**Comment by danielpclark** [comment]
I'm going to have a crack at this...  PR coming soon!

**Comment by tbrand** [comment]
Oh, that's a great feature!:tada:
I'm happy to waiting for this:smile:

**Comment by danielpclark** [comment]
How do you run the specs?  The `macro select_db(db)` isn't running for me.

**Comment by danielpclark** [comment]
It's done! :tada:
