### ISSUE TITLE
DB.open on each save?

### ISSUE THREAD

**Issue by asterite** [tbrand/topaz#2]
Is a DB connection opened on each save? Opening a connection is really, **really** slow. It should be done once in your application. I'm talking about [these lines](https://github.com/topaz-crystal/topaz/blob/5a767695fa5c63aaa8ab0b88ca11fbc4a78da8cc/src/topaz/model.cr#L242-L247).

I've made a benchmark:

```cr
require "benchmark"
require "pg"

DB.open "postgres:///" do |db|
  db.exec "drop table if exists contacts"
  db.exec "create table contacts (num integer)"
end

shared_db = DB.open "postgres:///"

Benchmark.ips do |x|
  x.report("open each time") do
    DB.open "postgres:///" do |db|
      db.exec "insert into contacts (num) values (1)"
    end
  end
  x.report("open once") do
    shared_db.exec "insert into contacts (num) values (1)"
  end
end
```

Results:

```
open each time  73.53  (  13.6ms) (± 4.26%) 58.82× slower
     open once   4.32k (231.23µs) (± 1.68%)       fastest
```

Almost 60 times slower to open and close a connection each time.

I'm not sure, but it could be the reason why you don't get very good performance [here](https://github.com/topaz-crystal/performance-evaluation/wiki/Performance-evaluation-with-Rails)

**Comment by tbrand** [comment]
You are right! I will fix it soon! :)
Thanks a lot!!

**Comment by tbrand** [comment]
Solved :)
Thanks again!
