### ISSUE TITLE
Time format and Postgres

### ISSUE THREAD

**Issue by jayroh** [tbrand/topaz#3]
After some testing and experimenting it looks like the default time format in the base Model class doesn't play nice with PG.

https://github.com/topaz-crystal/topaz/blob/master/src/topaz/model.cr#L9

Example using a sample table:

```sql
sampledb> insert into sample_table (name, created_at, updated_at) 
  values ('sdf', '2017-03-05 08:43:37.681', '2017-03-05 08:43:37.681');
INSERT 0 1
Time: 0.022s


sampledb> insert into sample_table (name, created_at, updated_at)
  values ('sdf', '2017-03-05 08:43:37:681', '2017-03-05 08:43:37:681');

invalid input syntax for type timestamp: "2017-03-05 08:43:37:681"
LINE 1: ...me, created_at, updated_at) values ('sdf', '2017-03-0...
```

First example using the period.  Second example using the colon.

I overridded it in my own project's base model class and that looks like it works fine

```crystal
require "topaz"

class SampleTable < Topaz::Model
  TIME_FORMAT = "%F %T.%L %z"
```

**Comment by tbrand** [comment]
Thanks!

In reference to your feedback, Topaz::Model::TIME_FORMAT will be deprecated in new version.
Please use Topaz::Db.time_format instead.

**Comment by tbrand** [comment]
I'v released a new version.
Please reopen this if the latest doesn't solve this issue.
