### ISSUE TITLE
Default values?

### ISSUE THREAD

**Issue by danielpclark** [tbrand/topaz#8]
Say I want to have a default value for a model schema.  Let's use a Todo app as an example:

```crystal
class Todo < Topaz::Model
  columns(
    description: String,
    completion: Time?
  )
end
```
The completion parameter should be assumed to be `nil` if no value is given unless `nullable: false` has be set as in https://github.com/topaz-crystal/topaz/blob/master/spec/model/models.cr#L48.

So if the union has a type of `Nil` in it I'd like the parameters in the `create` method to have `= nil` in it by default.  Again, to avoid that I'd use `nullable: false`.

As far as other default values I'm not sure how you'd want to do it.  Maybe something like?

```crystal
class Todo < Topaz::Model
  columns(
    description: String, {default: ""},
    attempts: Int32, {default: 0}
  )
end
```

**Comment by tbrand** [comment]
In the Topaz, actually, union is not accepted(even if the compiles are completed successfully) since we have to know the specific data type.
The only union allowed to be define is with Nil by using `nullable`.

Topaz restricts nullable or not by the constructor.
So if you need default values, it seems like this.
```crystal
todo = default_todo
todo.save

def default_todo
  Todo.new("", 0) # Todo.new() is not allowed
end
```

Does this make sense?

**Comment by danielpclark** [comment]
All I'm asking for is this:

```crystal
class Todo < Topaz::Model
  columns(
    description: {type: String, default: ""},
    completion: Time?,
    attempts: {type: Int32, default: 0}
  )
end
```

to expand to this:

```crystal
class Todo
  def initialize(description : String = "", completion : Time? = nil, attempts : Int32 = 0)
  end
end
```

This allows for `Todo.new()`

If you remove the `?` from `Time` it will remove the default so the above when changed will be:

```crystal
class Todo < Topaz::Model
  columns(
    description: {type: String, default: ""},
    completion: Time,
    attempts: {type: Int32, default: 0}
  )
end
```

expanded to this:

```crystal
class Todo
  def initialize(completion : Time, description : String = "", attempts : Int32 = 0)
  end
end
```

automatically setting the parameters with no default as the first ones.  Or if the order of the values are too important enforce keyword arguments.

```crystal
class Todo
  def initialize(*, description : String = "", completion : Time, attempts : Int32 = 0)
  end
end
```

**Comment by tbrand** [comment]
Oh I misunderstood, that's good idea.
Ordering arguments is too complex to implement in macro level, so I will add ` = somevalue` if default is set.
How does it sound to you?:smile:

**Comment by danielpclark** [comment]
Sounds great!

**Comment by danielpclark** [comment]
> Ordering arguments is too complex to implement in macro level

Since order is an issue for macros then it's okay to let those who use Topaz to define their columns so that items without defaults are always first.  Then there should be no problem.

**Comment by tbrand** [comment]
I agree:smile:
I will add the note to the sample code.

**Comment by danielpclark** [comment]
Question…

Shouldn't these be `= nil`

```crystal
{% if value[:default] %}
  @{{key.id}} : {{value[:type]}}? = {{value[:default]}},
{% else %}
  @{{key.id}} : {{value[:type]}}? = nil,
```

unless `{type: String, nullable: false},` is set?

---

**UPDATE**: Changed my mind.  This can be a separate issue if we want to change this.  It may cause unwanted behavior.

Just using `value[:default]` will work anyways.

**Comment by danielpclark** [comment]
Or do you think that would be too complex?

**Comment by danielpclark** [comment]
It's already under `{% if value[:nullable] %}` so I think each of the three points should be `= nil` without any issue.  No more complexity to add.  Do the other defaults still work on the `{% if !value[:nullable] %}` path?

**Comment by danielpclark** [comment]
I think the PR looks good! :+1:

**Comment by tbrand** [comment]
Oh, currently we cannot set like this
```crystal
columns(dummy: {type: String, nullable: true, default: nil})
```
[Here](https://github.com/topaz-crystal/topaz/pull/9/files#diff-63fa0bc21a262c0c1a4ab489a5552102R37) will be **false** then... 

I will add ` = nil` :smile:

OK, now `nullable` means `The column can be nil, and the default value of it is nil`.

**Comment by tbrand** [comment]
You can override the default value of the nullable column by using `default`.

**Comment by danielpclark** [comment]
Awesome!  This is what I was looking for. :smile:

**Comment by danielpclark** [comment]
Question… how do they set a `not_nil!` parameter required for a `Time?` type?  Or maybe that doesn't make sense :thinking:  

…

Perhaps the user can worry about that on their own with writing some sort of `validation` method. :man_shrugging:   In other-words, “we don't have to worry about it”.

**Comment by tbrand** [comment]
OK, it seems there are two discussions.

First, basically, union type is not allowed as column types since database column type have to be specific.
So `Time?` or `String|Int32` are not allowed. (But the compile will be completed successfully, that's a problem...)
Union of some specific type and Nil by using `{nullable: true}` is only allowed.

Second, validation is an awesome feature that Topaz should be implemented!!:smile:
I will add this feature in the next release.
Thanks for the good idea.

For the validation for nil or not, you can safety call it like
```
if completion_time = todo1.completion # <- For safety
  puts "Done at #{completion_time}"
end
```

Does this make sense?

**Comment by danielpclark** [comment]
>Second, validation is an awesome feature that Topaz should be implemented!!:smile:
> I will add this feature in the next release.
> Thanks for the good idea.

:clap: :tada: 

I understand all of this.  My thinking on the `Time?` validation (when the macro sets a default `= nil`) would have to be like:

Example:
```crystal
class Todo < Topaz::Model
  columns(
    completion: {type: Time, nullable: true} #  def initialize(completion : Time? = nil)
  )
end

class Todo < Topaz::Model
  # user needs to manually add validation here
  validates :completion, presence: true # not nil
end

Todo.create(completion: Time.new) # valid
Todo.create(completion: nil) # not valid
Todo.create() # not valid
```

You should be able to get what I'm saying about wanting a case where `nil` is not the default for a `nullable` situation.  You and I don't need to worry about it, the user can do it themselves.

So yeah, validation methods would be a nice feature for a **separate issue**/PR… and we might need it for this specific scenario I've described here.

**Comment by tbrand** [comment]
OK, I will think about the validations.
User can hook each getter of the model by their own validation methods...:smirk:

Anyway, thanks for the awosome advice :smile:
I will merge https://github.com/topaz-crystal/topaz/pull/9

**Comment by danielpclark** [comment]
You're missing one test case…

```crystal
with_nil_default2: String?, # The default value is `nil`
```

**Comment by danielpclark** [comment]
FYI, there is already a validations library available: https://github.com/neovintage/accord

Ideally validations will be for setter methods and new object creation.  In Ruby on Rails you can use invalid parameters with `new` but won't be able to call `save`.  Rails won't allow `create` to be called if the validations don't pass.

The **accord** library shown above is very similar to how Rails would do it.  If integrated into this project it would need to perform validations anytime a column (with a validation set on it) is to be changed (creation and setter methods).

**Comment by tbrand** [comment]
Oh, that's a good library.
I'll check it, thanks:smile:
